[package]
name = "bm_network"
version = "0.1.0"
edition = "2021"

[lib]
name = "bm_network"
path = "lib.rs"
crate-type = ["lib"]
test = true

[dependencies]
defmt = "0.3"
defmt-rtt = "0.4"
heapless = "0.8.0"
bitfield-struct = "0.9.2"
