name: Rust CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cross_compile:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust & Targets
      run: |
        rustup target add thumbv7m-none-eabi

    - name: Build
      run: cargo build --release --target=thumbv7m-none-eabi

    - name: Unit-Test
      run: cargo test -p bm_network --target x86_64-unknown-linux-gnu -- --nocapture
