name: Rust CI

on:
  workflow_dispatch:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Embedded Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust & Target
        run: rustup target add thumbv7m-none-eabi

      - name: Build Crate
        run: cargo build --release --target=thumbv7m-none-eabi

  test:
    name: Host Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Unit Tests
        run: cargo test -p bm_network --target x86_64-unknown-linux-gnu -- --nocapture
        