name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cross_compile:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
       echo "Removing MSVC toolchain file..."
       rm rust-toolchain.toml
       echo "Adding target compiler..."
       rustup target add thumbv7m-none-eabi
       rustup default stable-x86_64-unknown-linux-gnu
       cargo build --release --target=thumbv7m-none-eabi
# TODO - figure out unit tests
#    - name: Run tests
#      run: cargo test --verbose
