name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cross_compile:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
       echo "Adding target compiler..."
       rustup target add thumbv7m-none-eabi
       echo "Setting default target..."
       rustup default thumbv7m-none-eabi
       echo "Removing MSVC toolchain file..."
       rm rust-toolchain.toml
       cargo build --release
    - name: Run tests
      run: cargo test --verbose
